version: '3'

services:
  mongodb1:
    build:
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data1:/data/db
    networks:
      - mongodb_network

  mongodb2:
    build:
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    volumes:
      - mongo-data2:/data/db
    networks:
      - mongodb_network

  image:
    build:
      context: ./images
      dockerfile: Dockerfile
    volumes:
      - mongo-data:/data/db
    depends_on:
      - mongodb1
      - mongodb2
    networks:
      - image_network

volumes:
  mongo-data1:
  mongo-data2:

networks:
  mongodb_network:
  image_network:
